#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
SCRIPT_COMMAND="$0"
set -o nounset
set -o pipefail
set -o errexit

benchmarks=(
    "barnes|./BARNES < inputs/n16384-p#"
    "cholesky|./CHOLESKY -p# < inputs/tk15.O"
    "fft|./FFT -p# -m16"
    "fmm|./FMM < inputs/input.#.16384"
    "lu-contiguous_blocks|./LU-CONT -p# -n512"
    "lu-non_contiguous_blocks|./LU-NOCONT -p# -n512"
    "ocean-contiguous_partitions|./OCEAN-CONT -p# -n258"
    "ocean-non_contiguous_partitions|./OCEAN-NOCONT -p# -n258"
    "radiosity|./RADIOSITY -p # -ae 5000 -bf 0.1 -en 0.05 -room -batch"
    "radix|./RADIX -p# -n1048576"
    "raytrace|./RAYTRACE -p# -m64 inputs/car.env|inputs"
    "volrend|./VOLREND # inputs/head 8|inputs"
    "volrend-no_print_lock|./VOLREND-NPL # inputs/head 8|inputs"
    "water-nsquared|./WATER-NSQUARED < inputs/n512-p#|random.in"
    "water-spatial|./WATER-SPATIAL < inputs/n512-p#|random.in"
)

if [ $# -ge 2 ] ; then
    IFS=$'\n'
    read -r -a benchmarks <<< "$(printf "%s\n" "${benchmarks[@]}" | grep "^$2") )"
fi

if [ $# -ge 3 ] ; then
    IFS=" "
    read -r -a all_nprocs <<< "$3"
else
    all_nprocs=( 1 2 4 8 16 32 64 128 256 ) #512 1024 )
fi

spike_run_fs="${SPIKE_RUN_FS:-$(realpath "${SCRIPT_DIR}/../../spike-caps/riscv-isa-sim/spike-run-fs")}"
outdir=$(realpath "${1:-traces}")

[ -e "$outdir" ] && { echo "'$outdir' already exits" 2>&1 ; exit 1 ;}
mkdir "$outdir"

scripts=( )

for nprocs in "${all_nprocs[@]}" ; do
for b in "${benchmarks[@]}" ; do 
    dir="$(echo "$b" | cut -d "|" -f1)"
    cmd="$(echo "$b" | cut -d "|" -f2 | sed 's/#/'"$nprocs"'/g')"
    extra_files="$(echo "$b" | cut -d "|" -f3)"
    stdin="$(echo "$cmd" | grep -- ' < ' | perl -pe 's/.+ < (.+)/\1/')" || true
    IFS=' '
    read -r -a cmd <<< "$(echo "$cmd" | perl -pe 's/(.+) < .+/\1/' || true)"
    spike_run_args=(
        #--num-procs=$((nprocs + 1))
        --num-procs="$(sort -n <<< "$((nprocs + 1))"$'\n'"16" | head -n1)"
        -s-m16384 # ocean-nocont actaully needs this
        -s--log-g4trace
        -s--log-g4trace-dest="$outdir/$dir-$nprocs"
        #-s--log-g4trace-debug
    )
    if [ -n "$extra_files" ] ; then
        spike_run_args+=(--include-file="$extra_files")
    fi
    if [ -n "$stdin" ] ; then
        spike_run_args+=(--stdin "$stdin")
    fi
    full_cmd=( "${spike_run_fs}" "${spike_run_args[@]}" -- "${cmd[@]}" )
    script="$outdir/$dir-$nprocs.command"
    printf "#!/bin/bash\ncd %q\n%s\n" "$(realpath Splash-4/"$dir")" "$(printf "%q " "${full_cmd[@]}")" > "$script"
    chmod +x "$script"
    scripts+=("$script")
done
done

EXECUTE="no"

if [ "$EXECUTE" = "yes" ] ; then
    for s in "${scripts[@]}" ; do
        echo "Executing $(basename "$s" | sed 's/.command//'):"
        tail -n+2 "$s"
        time "$s"
        echo ""
    done
fi

# find "$outdir" -name '*command' | parallel --results results
